version: "3.8"
services:
  app:
    image: ghcr.io/asim3/my_project_name:${PROJECT_IMAGE_TAG}
    user: "1000:1000"
    environment:
      TZ: Asia/Riyadh
      MY___11111111111111: "22222222222222222222222222222222"
      MY___22222222222222: my Env
    secrets:
      - source: secret_swarmcd_key
        target: /home/swarmcd/.ssh/id_ecdsa
        uid: "1000"
        gid: "1000"
        mode: 0400

    deploy:
      mode: replicated
      replicas: 2
      labels:
        - traefik.enable=true
        - traefik.http.routers.my_project_name-app.rule=Host(`my_project_name.staging.asimt.sa`)
        - traefik.http.routers.my_project_name-app.tls=true
        - traefik.http.services.my_project_name-svc.loadbalancer.server.port=443
      resources:
        reservations:
          memory: 128M
        limits:
          memory: 2048M
      placement:
        constraints:
          - node.role == manager

    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

    networks:
      - main-public

    ports:
      - "8000:80"


networks:
  main-public:
    external: true


secrets:
  secret_swarmcd_key:
    external: true
