name: my_project_name CI

on:
  push:
    branches:
      - main

env:
  PROJECT_NAME: my_project_name
  PROJECT_IMAGE_NAME: "ghcr.io/asim3/${{ github.event.repository.name }}"


jobs:
  docker_test:
    runs-on: ubuntu-latest
    name: Test on Docker
    steps:
      - uses: actions/checkout@v4

      - name: Copy Env File
        run: cp ${PROJECT_NAME}/.env.sample ${PROJECT_NAME}/.env

      - name: Build Docker
        run: >
          GIT_REF=$(git rev-parse --verify HEAD);
          docker image build --no-cache
          -t ${PROJECT_IMAGE_NAME}:${GIT_REF}
          .

      - name: Run All Django Tests
        run: >
          GIT_REF=$(git rev-parse --verify HEAD);
          docker container run --rm
          -e DJANGO_SETTINGS_MODULE=${PROJECT_NAME}.settings.docker_dev
          ${PROJECT_IMAGE_NAME}:${GIT_REF} 'python3 manage.py test'


  docker_push:
    name: Push Docker Image
    needs: docker_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker
        run: >
          GIT_REF=$(git rev-parse --verify HEAD);
          docker image build --no-cache -t ${PROJECT_IMAGE_NAME}:${GIT_REF} . ;

      - name: Login To Container Registry
        env:
          GHCR_TOKEN: "${{ secrets.CONTAINER_REGISTRY_TOKEN }}"
        run: echo ${GHCR_TOKEN} | docker login ghcr.io --username asim3 --password-stdin

      - name: Push Image To Container Registry
        run: >
          docker image ls -a;
          GIT_REF=$(git rev-parse --verify HEAD);
          docker push ${PROJECT_IMAGE_NAME}:${GIT_REF};

      - name: Clean Up Docker Login
        if: always()
        run: rm -rf ~/.docker
