name: my_project_name Staging CD

on:
  push:
    tags:
      - staging-**

env:
  PROJECT_NAME: my_project_name
  DOCKER_HOST: "${{ vars.SSH_STAG_URI }}"
  SSH_HOST_KEY: "${{ vars.SSH_STAG_HOST_KEY }}"
  SSH_PRIVATE_KEY: ${{ secrets.SSH_STAG_PRIVATE_KEY }}

jobs:
  docker_deploy:
    name: Deploy To SWARM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add host to ssh/known_host file
        run: mkdir -p ~/.ssh && echo "$SSH_HOST_KEY" >> ~/.ssh/known_hosts

      - name: Deploy To Docker Station
        run: >
          GIT_REF=$(git rev-parse --verify HEAD)
          && export PROJECT_IMAGE_TAG=${GIT_REF}
          && eval "$(ssh-agent -s)"
          && ssh-add - <<< $SSH_PRIVATE_KEY
          && docker stack deploy -c ./deploy/docker-compose.yml    ${PROJECT_NAME}

      - name: Clean Up SSH
        if: always()
        run: rm -rf ~/.ssh
