name: my_project_name Staging CD

on:
  push:
    tags:
      - staging-**

env:
  PROJECT_NAME: my_project_name
  PROJECT_IMAGE_NAME: "ghcr.io/asim3/${{ github.event.repository.name }}"


jobs:
  docker_deploy:
    name: Deploy To SWARM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update Stack Image Tag
        run: >
          GIT_REF=$(git rev-parse --verify HEAD);
          echo ${PROJECT_IMAGE_NAME};
          echo ${GIT_REF}

      - name: Commite the change
        run: >
          ls -al ./

      - name: Make new release
        run: >
          ls -al ./

      - name: Deploy Stack to SWARM
        run: >
          ls -al ./

      - name: Clean Up Docker Login
        if: always()
        run: rm -rf ~/.docker
