# Generated by Django 3.2 on 2022-06-13 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='is_verified',
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='key',
            field=models.CharField(max_length=4, verbose_name='key'),
        ),
    ]
