version: "3.8"

services:
  postgresql:
    image: postgres
    restart: unless-stopped
    container_name: my_project_name-db
    volumes:
      - my_project_name-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=pg_db
      - POSTGRES_USER=pg_user
      - POSTGRES_PASSWORD=pg_pass
 
  app:
    build: .
    container_name: my_project_name
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    environment:
      - DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
      - DATABASE_URL=postgres://pg_user:pg_pass@postgresql:5432/pg_db

volumes:
  my_project_name-db:
