version: "3.8"

services:
  postgres:
    image: postgres
    restart: unless-stopped
    volumes:
      - my_project_name-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=psql-db
      - POSTGRES_USER=psql-user
      - POSTGRES_PASSWORD=psql-pass

  migrate:
    build: .
    command: python manage.py migrate
    environment:
      - DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
      - DJANGO_SECRET_KEY="top-secret"
      - DJANGO_DEBUG=True
      - REST_SIGNING_KEY="rest-top-secret"
      - DATABASE_URL=postgresql://psql-user:psql-pass@postgres-compose:5432/psql-db
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started

  collect_static:
    build: .
    command: python manage.py collectstatic --noinput
    environment:
      - DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
      - DJANGO_SECRET_KEY="top-secret"
      - DJANGO_DEBUG=True
      - REST_SIGNING_KEY="rest-top-secret"
      - DATABASE_URL=postgresql://psql-user:psql-pass@postgres-compose:5432/psql-db
    restart: on-failure
    depends_on:
      postgres:
        condition: service_started

  app:
    build: .
    environment:
      - DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
      - DJANGO_SECRET_KEY="top-secret"
      - DJANGO_DEBUG=True
      - REST_SIGNING_KEY="rest-top-secret"
      - DATABASE_URL=postgresql://psql-user:psql-pass@postgres-compose:5432/psql-db
    ports:
      - "8000:8000"
    depends_on:
      migrate:
        condition: service_completed_successfully
      collect_static:
        condition: service_completed_successfully


volumes:
  my_project_name-db-data:
