version: "3.3"
# https://testdriven.io/blog/dockerizing-django-with-postgres-gunicorn-and-nginx/#gunicorn

services:
  postgres-compose:
    image: postgres
    restart: unless-stopped
    container_name: my_project_name-db
    volumes:
      - ./compose-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=psql-db
      - POSTGRES_USER=psql-user
      - POSTGRES_PASSWORD=psql-pass

  django-compose:
    build: .
    container_name: my_project_name-app
    ports:
      - "8000:8000"
    depends_on:
      - postgres-compose
    environment:
      - DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
      - DJANGO_SECRET_KEY="top-secret"
      - DJANGO_DEBUG=True
      - REST_SIGNING_KEY="rest-top-secret"
      - DATABASE_URL=postgresql://psql-user:psql-pass@postgres-compose:5432/psql-db
