version: "3.8"

services:
  postgresql:
    image: postgres
    restart: unless-stopped
    container_name: my_project_name-db
    environment:
      - POSTGRES_DB=db_pg
      - POSTGRES_USER=user_pg
      - POSTGRES_PASSWORD=pass_pg
    volumes:
      - my_project_name-db:/var/lib/postgresql/data
 
  app-migrate:
    build: .
    container_name: my_project_name-migrate
    entrypoint:
      - "/bin/sh"
      - "-c"
      - "python manage.py migrate && python manage.py collectstatic --no-input"
    depends_on:
      - postgresql
    environment:
      - DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
    volumes:
      - ./my_project_name:/home/d_user/web
 
  app:
    build: .
    container_name: my_project_name
    ports:
      - "8000:8000"
    depends_on:
      - app-migrate
    environment:
      - DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
    volumes:
      - ./my_project_name:/home/d_user/web

volumes:
  my_project_name-db:
