version: "3.3"

services:
  my-db-postgres:
    image: postgres
    restart: unless-stopped
    container_name: my-db-postgres
    volumes:
      - ./compose-data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  django-compose:
    build: .
    container_name: django-compose
    ports:
      - "8000:8000"
    depends_on:
      - my-db-postgres
    environment:
      - DJANGO_SECRET_KEY="top-secret"
      - DJANGO_DEBUG=True
      - DJANGO_ALLOWED_HOSTS=*,127.0.0.1,localhost
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
