version: "3.8"

services:
  postgresql:
    image: postgres
    restart: unless-stopped
    container_name: my_project_name-db
    volumes:
      - my_project_name-db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=db_pg
      - POSTGRES_USER=user_pg
      - POSTGRES_PASSWORD=pass_pg
 
  app:
    build: .
    container_name: my_project_name
    ports:
      - "8000:8000"
    depends_on:
      - postgresql
    environment:
      - DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
      - DATABASE_URL=postgres://user_pg:pass_pg@postgresql:5432/db_pg

volumes:
  my_project_name-db:
