name: Run All Django Tests
on: [ push ]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.8', '3.9', '3.x']
    name: Test on Python ${{ matrix.python-version }}
    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      
      - name: Create New Django Project
        run: if [ -x ./setup/set-new-django-project.bash ]; then echo "test_project" | ./setup/set-new-django-project.bash; fi;
      
      - name: Install requirements
        run: make install
      
      - name: Run All Tests
        run: make tests
