name: my_project_name CI/CD

on:
  push:
    tags:
      - v-**

env:
  PROJECT_NAME: "${{ github.event.repository.name }}"
  DATABASE_URL: postgresql://user_6:my-pass-6@192.168.122.161:5432/new_db_6

jobs:
  docker_build:
    runs-on: "${{ github.event.repository.name }}-staging-runner-v3"
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        run: >
          docker image build --no-cache
          -t asim3/${PROJECT_NAME}:${GITHUB_REF_NAME:2}
          -t asim3/${PROJECT_NAME}:latest
          .


  docker_push:
    runs-on: "${{ github.event.repository.name }}-staging-runner-v3"
    name: Push Image To Docker Hub
    needs: docker_build
    steps:
      - name: Push Image
        run: docker push asim3/${PROJECT_NAME}:${GITHUB_REF_NAME:2}

      - name: Push Latest Image
        run: docker push asim3/${PROJECT_NAME}:latest


  database_backup:
    runs-on: "${{ github.event.repository.name }}-staging-runner-v3"
    name: Backup The Prod Database
    needs: docker_push
    steps:
      - name: Backup Staging Database
        run: pg_dump ${DATABASE_URL} > ~/backup.${GITHUB_REF_NAME:2}.sql


  database_restore:
    runs-on: "${{ github.event.repository.name }}-staging-runner-v3"
    name: Restore The Staging Database
    needs: database_backup
    steps:
      - name: Restore Staging Database
        run: psql ${DATABASE_URL} -c "\l"
        # run: psql ${DATABASE_URL} < ~/backup.${GITHUB_REF_NAME:2}.sql


  # database_migrate:
  #   runs-on: "${{ github.event.repository.name }}-staging-runner-v3"
  #   name: Migrate The Staging Database
  #   needs: database_restore
  #   steps:
  #     - name: Migrate Database
  #       run: python manage.py migrate

  #     - name: Collect Static
  #       run: python manage.py collectstatic --noinput


  update_stack:
    runs-on: "${{ github.event.repository.name }}-staging-runner-v3"
    name: Update Swarm Prod Stack
    # TODO: needs: database_migrate
    needs: docker_push
    steps:
      - name: Update Swarm Stack File
        run: >
          curl -L
          -X POST
          -H "Accept: application/vnd.github+json"
          -H "Authorization: Bearer ${GITHUB_TOKEN}"
          -H "X-GitHub-Api-Version: 2022-11-28"
          https://api.github.com/repos/asim3/aaaaaaaaaaa/actions/workflows/swarm-cd.yml/dispatches
          -d '{"ref":"main","inputs":{"stack_file":"'${PROJECT_NAME}'","image_tag":"'${GITHUB_REF_NAME:2}'"}}'
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_ACTIONS_WRITE }}
