name: Build & Push Docker

on:
  push:
    tags:
      - v-**

jobs:
  docker_build:
    runs-on: ubuntu-latest
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        run: >
          docker image build
          -t asim3/my_project_name:${GITHUB_REF_NAME:2}
          -t asim3/my_project_name:latest
          .

      - name: List Docker Images
        run: docker image ls

      - name: Run All Django Tests
        run: docker run asim3/my_project_name:${GITHUB_REF_NAME:2} /bin/sh -c 'python3 manage.py test'

#   docker_push:
#     runs-on: ubuntu-latest
#     name: Push Image To Docker Hub
#     needs: docker_build
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Push
#         run: docker push asim3/my_project_name:${GITHUB_REF_NAME:2}

#       - name: Push Latest
#         run: docker push asim3/my_project_name:latest

#   database_backup:
#     runs-on: ubuntu-latest
#     name: Backup The Prod Database
#     needs:
#       - docker_build
#       - docker_push
#     if: ${{ always() }}
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v3

#       - name: Backup Staging Database
#         run: pg_dump postgresql://user_6:my-pass-6@192.168.122.161:5432/new_db_6 > /tmp/my_workflow_backup.0.sql

#       - name: Restore Staging Database
#         run: pg_dump postgresql://user_6:my-pass-6@192.168.122.161:5432/new_db_6 > /tmp/my_workflow_backup.0.sql

#       - name: Migrate Database
#         run: python manage.py migrate

#       - name: Collect Static
#         run: python manage.py collectstatic --noinput
