name: my_project_name Push Tests

on:
  push:
    branches:
      - main

jobs:
  docker_test:
    runs-on: ubuntu-latest
    name: Test on Docker
    steps:
      - uses: actions/checkout@v3

      - name: Create New Django Project
        run: if [ -x ./setup/set-new-django-project.bash ]; then echo "test_project" | make init; fi;


      - name: Copy Env File
        run: cp my_project_name/.env-example my_project_name/.env

      - name: Build Docker
        run: >
          GIT_REF=$(git rev-parse --verify HEAD);
          docker image build --no-cache
          -t asim3/my_project_name:${GIT_REF}
          .

      - name: Run All Django Tests
        run: >
          GIT_REF=$(git rev-parse --verify HEAD);
          docker container run --rm
          -e DJANGO_SETTINGS_MODULE=my_project_name.settings.docker_dev
          asim3/my_project_name:${GIT_REF} 'python3 manage.py test'
