name: my_project_name CI/CD

on:
  push:
    tags:
      - v-**

jobs:
  docker_build:
    runs-on: my_project_name-staging-runner-v3
    name: Build Docker Image
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build Image
        run: >
          docker image build --no-cache
          -t asim3/my_project_name:${GITHUB_REF_NAME:2}
          -t asim3/my_project_name:latest
          .


  docker_push:
    runs-on: my_project_name-staging-runner-v3
    name: Push Image To Docker Hub
    needs: docker_build
    steps:
      - name: Push Image
        run: docker push asim3/my_project_name:${GITHUB_REF_NAME:2}

      - name: Push Latest Image
        run: docker push asim3/my_project_name:latest


  database_backup:
    runs-on: my_project_name-staging-runner-v3
    name: Backup The Prod Database
    needs: docker_push
    steps:
      - name: Backup Staging Database
        run: pg_dump postgresql://user_6:my-pass-6@192.168.122.161:5432/new_db_6 > ~/backup.${GITHUB_REF_NAME:2}.sql

#       - name: Restore Staging Database
#         run: pg_dump postgresql://user_6:my-pass-6@192.168.122.161:5432/new_db_6 > /tmp/my_workflow_backup.0.sql

#       - name: Migrate Database
#         run: python manage.py migrate

#       - name: Collect Static
#         run: python manage.py collectstatic --noinput
